---
# Common code for bluetooth proxies
# BLE scanning wait/pause for WIFI, needed on single core chips (esp32-c3/s2) but probably
# helpful for others (have seen "Too many BLE events to process." on esp32-s3 modules)

esp32_ble_tracker:
  id: ble_tracker
  scan_parameters:
    continuous: false  # will only be enabled when api is connected, helps w/ wifi connection, see api: below
    interval: 211ms  # default 320ms
    window: 120ms    # default 30ms
    active: true
    # default scan interval may be to intensive
    # scan_parameters:
    #  interval: 1100ms
    #  window: 1100ms
    #  active: true

bluetooth_proxy:
  id: ble_proxy
  active: true

api:
  # start ble_tracker scanning when api is connected and stop when disconnected
  # helps resolve issues connecting to wifi on singe core boards
  on_client_connected:
    - esp32_ble_tracker.start_scan:
        continuous: true
  on_client_disconnected:
    if:
      condition:
        not:
          api.connected:
      then:
        - esp32_ble_tracker.stop_scan:
