---
# I²C Bus
#
# This component sets up the I²C bus for the ESP32.
#
# GPIO defaults:
#     esp32: SDA - GPIO21, SLC - GPIO22
#   esp8266: SDA - GPIO4,  SLC - GPIO5
#
# https://esphome.io/components/i2c.html

substitutions:
  i2c_sda: GPIO21
  i2c_slc: GPIO22

i2c:
  sda: ${i2c_sda}
  scl: ${i2c_scl}
