---
# I²C Bus
#
# This component sets up the I²C bus using the default pins
#
# GPIO defaults:
#     esp32: SDA - GPIO21, SLC - GPIO22
#   esp8266: SDA - GPIO4,  SLC - GPIO5
#
# https://esphome.io/components/i2c.html
#
i2c:
  sda: ${i2c_sda}
  scl: ${i2c_scl}
  frequency: 400kHz  # 400kHz eliminates warnings about many i2c components taking a long time: https://github.com/esphome/issues/issues/4717
