#
# substitutions:
#  ld2450_tx_pin: <TX GPIO PIN>
#  ld2450_rx_pin: <RX GPIO PIN>
#

external_components:
  - source: github://pr#5674
    components: [ ld2450 ]

logger:
  baud_rate: 0

uart:
  id: uart_ld2450
  tx_pin: ${ld2450_tx_pin}
  rx_pin: ${ld2450_rx_pin}
  baud_rate: 256000
  parity: NONE
  stop_bits: 1

ld2450:
  id: ld2450_radar
  uart_id: uart_ld2450
  throttle: 1000ms

binary_sensor:
  - platform: ld2450
    ld2450_id: ld2450_radar
    has_target:
      name: ${friendly_name} Presence
    has_moving_target:
      name: ${friendly_name} Moving Target
    has_still_target:
      name: ${friendly_name} Still Target

number:
  - platform: ld2450
    ld2450_id: ld2450_radar
    presence_timeout:
      name: "${friendly_name} Timeout"
    zone_1:
      x1:
        name: ${friendly_name} Zone-1 X1
      y1:
        name: ${friendly_name} Zone-1 Y1
      x2:
        name: ${friendly_name} Zone-1 X2
      y2:
        name: ${friendly_name} Zone-1 Y2
    zone_2:
      x1:
        name: ${friendly_name} Zone-2 X1
      y1:
        name: ${friendly_name} Zone-2 Y1
      x2:
        name: ${friendly_name} Zone-2 X2
      y2:
        name: ${friendly_name} Zone-2 Y2
    zone_3:
      x1:
        name: ${friendly_name} Zone-3 X1
      y1:
        name: ${friendly_name} Zone-3 Y1
      x2:
        name: ${friendly_name} Zone-3 X2
      y2:
        name: ${friendly_name} Zone-3 Y2
  # addition for EPL
  - platform: template
    name: "${friendly_name} Illuminance Offset"
    id: illuminance_offset_ui
    unit_of_measurement: "lx"
    min_value: -100
    max_value: 100
    step: 5
    mode: slider
    update_interval: never
    optimistic: true
    restore_value: true
    initial_value: 0
    icon: "mdi:brightness-5"
    entity_category: config
    on_value:
      - lambda: 'id(illuminance_sensor).update();'

switch:
  - platform: ld2450
    ld2450_id: ld2450_radar
    bluetooth:
      name: "${friendly_name} Bluetooth"
    multi_target:
      name: "${friendly_name} Multi Target Tracking"

select:
  - platform: ld2450
    ld2450_id: ld2450_radar
    baud_rate:
      name: "${friendly_name} Baud rate"
    zone_type:
      name: "${friendly_name} Zone Type"

text_sensor:
  - platform: ld2450
    ld2450_id: ld2450_radar
    version:
      name: "${friendly_name} LD2450 Firmware"
    mac_address:
      name: "${friendly_name} LD2450 BT MAC"
    target_1:
      direction:
        name: "${friendly_name} Target-1 Direction"
        id: target1_direction
    target_2:
      direction:
        name: "${friendly_name} Target-2 Direction"
        id: target2_direction
    target_3:
      direction:
        name: "${friendly_name} Target-3 Direction"
        #id: target3_direction

sensor:
  - platform: ld2450
    ld2450_id: ld2450_radar
    target_count:
      name: ${friendly_name} Presence Target Count
      id: presence_target_count
    still_target_count:
      name: ${friendly_name} Still Target Count
      id: still_target_count
    moving_target_count:
      name: ${friendly_name} Moving Target Count
      id: moving_target_count
    target_1:
      x:
        name: ${friendly_name} Target-1 X
        id: target1_x
      y:
        name: ${friendly_name} Target-1 Y
        id: target1_y
      speed:
        name: ${friendly_name} Target-1 Speed
        id: target1_speed
      angle:
        name: ${friendly_name} Target-1 Angle
        id: target1_angle
      distance:
        name: ${friendly_name} Target-1 Distance
        id: target1_distance
      resolution:
        name: ${friendly_name} Target-1 Resolution
        id: target1_resolution
    target_2:
      x:
        name: ${friendly_name} Target-2 X
        id: target2_x
      y:
        name: ${friendly_name} Target-2 Y
        id: target2_y
      speed:
        name: ${friendly_name} Target-2 Speed
        id: target2_speed
      angle:
        name: ${friendly_name} Target-2 Angle
        id: target2_angle
      distance:
        name: ${friendly_name} Target-2 Distance
        id: target2_distance
      resolution:
        name: ${friendly_name} Target-2 Resolution
        id: target2_resolution
    target_3:
      x:
        name: ${friendly_name} Target-3 X
        id: target3_x
      y:
        name: ${friendly_name} Target-3 Y
        id: target3_y
      speed:
        name: ${friendly_name} Target-3 Speed
        id: target3_speed
      angle:
        name: ${friendly_name} Target-3 Angle
        id: target3_angle
      distance:
        name: ${friendly_name} Target-3 Distance
        id: target3_distance
      resolution:
        name: ${friendly_name} Target-3 Resolution
        id: target3_resolution
# Below are additions from for the EPL not in the PR example code above  
  - platform: bh1750
    name: ${friendly_name} Illuminance
    id: illuminance_sensor
    address: 0x23
    update_interval: ${illuminance_update_interval}
    filters:
      - lambda: "return x + id(illuminance_offset_ui).state;"

light:
  - platform: status_led
    name: ${friendly_name} ESP32 LED
    pin: GPIO14
    internal: False
    restore_mode: ALWAYS_OFF
