#
# substitutions:
#  ld2450_tx_pin: <TX GPIO PIN>
#  ld2450_rx_pin: <RX GPIO PIN>
#

external_components:
  - source: github://pr#5674
    components: [ ld2450 ]

logger:
  baud_rate: 0

uart:
  id: uart_ld2450
  tx_pin: ${ld2450_tx_pin}
  rx_pin: ${ld2450_rx_pin}
  baud_rate: 256000
  parity: NONE
  stop_bits: 1

ld2450:
  id: ld2450_radar
  uart_id: uart_ld2450
  throttle: 1000ms

binary_sensor:
  - platform: ld2450
    ld2450_id: ld2450_radar
#    has_target:
#      name: Presence
#    has_moving_target:
#      name: Moving Target
#    has_still_target:
#      name: Still Target
#
number:
  - platform: ld2450
    ld2450_id: ld2450_radar
    presence_timeout:
      name: "Timeout"
#
switch:
  - platform: ld2450
    ld2450_id: ld2450_radar
#    bluetooth:
#      name: "Bluetooth"
#    multi_target:
#      name: "Multi Target Tracking"
#
select:
  - platform: ld2450
    ld2450_id: ld2450_radar
#    baud_rate:
#      name: "Baud rate"
#    zone_type:
#      name: "Zone Type"
#
text_sensor:
  - platform: ld2450
    ld2450_id: ld2450_radar
#    version:
#      name: "LD2450 Firmware"
#    mac_address:
#      name: "LD2450 BT MAC"
#    target_1:
#      direction:
#        name: "Target-1 Direction"
#    target_2:
#      direction:
#        name: "Target-2 Direction"
#    target_3:
#      direction:
#        name: "Target-3 Direction"
#
sensor:
  - platform: ld2450
    ld2450_id: ld2450_radar
#    target_count:
#      name: Presence Target Count
#    still_target_count:
#      name: Still Target Count
#    moving_target_count:
#      name: Moving Target Count
#
