#
# substitutions:
#  ld2450_tx_pin: <TX GPIO PIN>
#  ld2450_rx_pin: <RX GPIO PIN>
#

external_components:
  - source: github://pr#5674
    components: [ ld2450 ]

logger:
  baud_rate: 0

uart:
  id: uart_ld2450
  tx_pin: ${ld2450_tx_pin}
  rx_pin: ${ld2450_rx_pin}
  baud_rate: 256000
  parity: NONE
  stop_bits: 1

ld2450:
  id: ld2450_radar
  uart_id: uart_ld2450
  throttle: 1000ms

binary_sensor:
  - platform: ld2450
    ld2450_id: ld2450_radar
    has_target:
      name: Presence
    has_moving_target:
      name: Moving Target
    has_still_target:
      name: Still Target

number:
  - platform: ld2450
    ld2450_id: ld2450_radar
    presence_timeout:
      name: "Timeout"
    zone_1:
      x1:
        name: Zone-1 X1
        id: zone1_x1
      y1:
        name: Zone-1 Y1
        id: zone1_y1
      x2:
        name: Zone-1 X2
        id: zone1_x2
      y2:
        name: Zone-1 Y2
        id: zone1_y2
    zone_2:
      x1:
        name: Zone-2 X1
        id: zone2_x1
      y1:
        name: Zone-2 Y1
        id: zone2_y1
      x2:
        name: Zone-2 X2
        id: zone2_x2
      y2:
        name: Zone-2 Y2
        id: zone2_y2
    zone_3:
      x1:
        name: Zone-3 X1
        id: zone3_x1
      y1:
        name: Zone-3 Y1
        id: zone3_y1
      x2:
        name: Zone-3 X2
        id: zone3_x2
      y2:
        name: Zone-3 Y2
        id: zone3_y2
  # addition for EPL
  - platform: template
    name: "Illuminance Offset"
    id: illuminance_offset_ui
    unit_of_measurement: "lx"
    min_value: -100
    max_value: 100
    step: 5
    mode: slider
    update_interval: never
    optimistic: true
    restore_value: true
    initial_value: 0
    icon: "mdi:brightness-5"
    entity_category: config
    on_value:
      - lambda: 'id(illuminance_sensor).update();'

switch:
  - platform: ld2450
    ld2450_id: ld2450_radar
    bluetooth:
      name: "Bluetooth"
    multi_target:
      name: "Multi Target Tracking"

select:
  - platform: ld2450
    ld2450_id: ld2450_radar
    baud_rate:
      name: "Baud rate"
    zone_type:
      name: "Zone Type"

text_sensor:
  - platform: ld2450
    ld2450_id: ld2450_radar
    version:
      name: "LD2450 Firmware"
    mac_address:
      name: "LD2450 BT MAC"
    target_1:
      direction:
        name: "Target-1 Direction"
        id: target1_direction
    target_2:
      direction:
        name: "Target-2 Direction"
        id: target2_direction
    target_3:
      direction:
        name: "Target-3 Direction"
        id: target3_direction

sensor:
  - platform: ld2450
    ld2450_id: ld2450_radar
    target_count:
      name: Presence Target Count
      id: presence_target_count
    still_target_count:
      name: Still Target Count
      id: still_target_count
    moving_target_count:
      name: Moving Target Count
      id: moving_target_count
    target_1:
      x:
        name: Target-1 X
        id: target1-x
      y:
        name: Target-1 Y
        id: target1-y
      speed:
        name: Target-1 Speed
        id: target1_speed
      angle:
        name: Target-1 Angle
        id: target1_angle
      distance:
        name: Target-1 Distance
        id: target1_distance
      resolution:
        name: Target-1 Resolution
        id: target1_resolution
    target_2:
      x:
        name: Target-2 X
        id: target2-x
      y:
        name: Target-2 Y
        id: target2-y
      speed:
        name: Target-2 Speed
        id: target2-speed
      angle:
        name: Target-2 Angle
        id: target2-angle
      distance:
        name: Target-2 Distance
        id: target2-distance
      resolution:
        name: Target-2 Resolution
        id: target2-resolution
    target_3:
      x:
        name: Target-3 X
        id: target3-x
      y:
        name: Target-3 Y
        id: target3-y
      speed:
        name: Target-3 Speed
        id: target3-speed
      angle:
        name: Target-3 Angle
        id: target3-angle
      distance:
        name: Target-3 Distance
        id: target3-distance
      resolution:
        name: Target-3 Resolution
        id: target3-resolution
# Below are additions from for the EPL not in the PR example code above  
  - platform: bh1750
    name: Illuminance
    id: illuminance_sensor
    address: 0x23
    update_interval: ${illuminance_update_interval}
    filters:
      - lambda: "return x + id(illuminance_offset_ui).state;"

light:
  - platform: status_led
    name: ESP32 LED
    pin: GPIO14
    internal: False
    restore_mode: ALWAYS_OFF
