---
# *** use with the lvgl-antiburn-time.yaml component
#
# display_id substitution needs to be set in device yaml this
# is included from so 'component.update' works
# ** removed component.update for now, so display_id sub can maybe be removed?
#
# if things don't update as expected when resuming in the 'lvgl:'' component add
# an 'on_resume:' that calls a script or other action that will force a update

- platform: template
  name: Antiburn
  id: switch_antiburn
  icon: mdi:television-shimmer
  optimistic: true
  entity_category: "config"
  turn_on_action:
    - logger.log: "Starting Antiburn"
    - if:
        condition: lvgl.is_paused
        then:
          - lvgl.resume:
          - lvgl.widget.redraw:
    - lvgl.pause:
        show_snow: true
  turn_off_action:
    - logger.log: "Stopping Antiburn"
    - if:
        condition: lvgl.is_paused
        then:
          - lvgl.resume:
          - lvgl.widget.redraw:

