---
# On boad LED (for devices like the Lolin C3 mini)
#
# To use add:
#
# light:
#   - << !include components/onboard_ws2812.yaml
#
# AND
# substitutions:
#   onboard_led_gpio: GPIO7
#   onboard_led_rgb_order: GRB
# 
# These are all set w/ substitutions in each of the <board>.yaml files. 
# Lolin C3 mini:      Lolin S3 mini:      Lolin S3
# led_gpio: GPIO7     led_gpio: GPI47     led_gpio: GPIO38
# led_rgb_order: GRB  led_rgb_order: RGB  led_rgb_order: GRB

- platform: esp32_rmt_led_strip
  id: onboard_led
  name: "${name} Led"
  rgb_order: GRB
  chipset: WS2812
  rmt_channel: 0
  num_leds: 1
  pin: ${onboard_led_gpio}

# Below doesn't work with framework: esp-idf
# platform: neopixelbus
# name: "${name} led"
# id: ${device_id}_led
# # restore_mode: ALWAYS_ON
# type: GRB
# variant: WS2812
# method: ESP32_RMT_1
# # method: ESP32_RMT
# num_leds: 1
# pin: ${onboard_led_gpio}

