---
# Web Server component
#
# The web_server component creates a simple web server on the node that can be
# accessed through any browser and a simple REST API. Please note that enabling
# this component will take up a lot of memory and can lead to problems,
# especially on the ESP8266.
#
# https://esphome.io/components/web_server.html

# to resolve issues with secrets, added a secrets.yaml file in the same directory
# as this file with '<<: !included ../common/secret.yaml'
# trying that here didn't work ¯\_(ツ)_/¯

web_server:
  id: component_web_server
  auth:
    username: !secret web_server_username
    password: !secret esphome_web_server_password
