---
#
# BH1750 Ambient Light Sensor
#
# The bh1750 sensor platform allows you to use your BH1750 (datasheet) ambient light sensor with ESPHome
#
# https://esphome.io/components/sensor/bh1750.html
#
# connections:
# sda I²C bus data line - usually defaults to GPIO21 for ESP32 and GPIO4 for ESP8266
# scl I²C bus clock line - usually defaults to GPIO22 for ESP32 and GPIO5 for ESP8266

platform: bh1750
name: "${name} Illuminance"
# update_interval defaults to 60s
#update_interval: 60s

