substitutions:
  device_name: basement-plug-0
  name: Basement Plug 0
  description: Basement Plug (Cloudfree SmartPlug2)
  switch_restore_mode: ALWAYS_OFF
  #switch_restore_mode: RESTORE_DEFAULT_OFF
  #wattage_calibration: 67.6 -> 11.0
  #amperage_calibration: 0.12 -> 0.08
  #voltage_calibration1: 0.0 -> 0.0
  #voltage_calibration2: 322.4 -> 118.3

packages:
  device: !include devices/aoycocr_x10s_common.yaml

