---
# {{...}}=needs replacement
# {{DESCRIPTION}}

substitutions:
  device_name: bedroom-multisensor0
  name: Primary Bedroom Multisensor0
  device_id: primary_bedroom_multisensor0
  description: Primary bedroom bed, temp, light sensors
  i2c_sda: GPIO42
  i2c_scl: GPIO41
  #bed_sensor_gpio: GPIO13
  #bed_sensor_gpio: A12 # (GPIO13)
  bed_sensor_gpio: GPIO1
  bed_sensor_delta: '1.5'
  onboard_led_gpio: GPIO38

packages:
  <<: !include_dir_named common
  board: !include boards/lolin_s3.yaml
  i2c: !include components/i2c.yaml

<<: !include components/bluetooth_proxy+tracker.yaml

esphome:
  # turn on onboad led to red w/ brightness %
  # (dimmest is 11%, 12% turns on more reliably, off ≤ 10%)
  on_boot:
    priority: 600 # default
    then:
      - delay: 2s
      - light.turn_on:
          id: onboard_led
          brightness: 25%
          red: 100%
          green: 0%
          blue: 100%
      - delay: 7s
      - light.turn_on:
          id: onboard_led
          brightness: 11%
          red: 100%
          green: 0%
          blue: 0%

#Enable logging
logger:
  hardware_uart: UART1
#  baud_rate: 0 #disable UART logging

light:
  <<: !include components/onboard_ws2812.yaml

sensor:
  - <<: !include sensors/shtcx.yaml
  - <<: !include sensors/bh1750.yaml
  - <<: !include sensors/bed_sensor.yaml
  - platform: homeassistant
    name: "${name} Bed Trigger Level"
    id: "${device_id}_bed_trigger_level"
    entity_id: input_number.${device_id}_bed_trigger_level

binary_sensor:
  - platform: template
    name: "${name} Bed Occupied"
    device_class: occupancy
    id: ${device_id}_bed_occupancy
    # Checks to see if voltage is lower than the trigger level set via input number, if so it sets left bed side to occupied
    lambda: |-
      if (id(${device_id}_bed_sensor).state < id(${device_id}_bed_trigger_level).state) {
        return true;
      } else {
        return false;
      }
