
substitutions:
  device_name: bedroom-heat-pump
  device_id: bedroom_heat_pump
  description: Primary bedroom heat pump
  name: Bedroom heat pump

packages:
  <<: !include_dir_named common
  board: !include boards/esp32doit-devkit-v1.yaml

external_components:
  #- source: github://geoffdavis/esphome-mitsubishiheatpump@develop # archived/depricated use echavet's which maintains same functionality 
  - source: github://echavet/MitsubishiCN105ESPHome # https://github.com/echavet/MitsubishiCN105ESPHome

esphome:
  # Set platform options to use c++ 17 instead of 11
  platformio_options:
    build_unflags:
      - "-std=gnu++11"
    build_flags:
      - "-std=gnu++17"

  #on_boot:
  #  then:
  #    - delay: 2s
  #    - light.turn_on:
  #        id: ${device_id}_led
  #        brightness: 15%

#light:
#  - platform: neopixelbus
#    id: ${device_id}_led
#    #restore_mode: ALWAYS_ON
#    type: GRB
#    variant: WS2812
#    method: ESP32_RMT_1
#    #method: ESP32_RMT
#    num_leds: 1
#    pin: GPIO7
#    name: "Bedroom heatpump led"
#    # hack to reduce brightness, now set using 'on_boot:'
#    #color_correct: [11%, 11%, 11%]

# this works around a bug introduced in HA 2025.5.0
sensor:
  - platform: uptime
    name: Uptime

uart:
  id: hp_uart
  baud_rate: 2400
  tx_pin: 12
  rx_pin: 13

climate:
  #- platform: mitsubishi_heatpump
  - platform: cn105
    # using "name: none" uses friendly name
    name: "${name}"
    id: ${device_id}_climate
    visual:
      temperature_step: 1.0

