---
substitutions:
  device_name: bedroom-tracker
  name: "Bedroom tracker"
  description: Primary bedroom ble proxy & device tracker

packages:
  <<: !include_dir_named common
  board: !include boards/lolin_s3_mini.yaml

<<: !include components/bluetooth_proxy+tracker-ble-wait-wifi.yaml

esphome:
  on_boot:
    then:
      - delay: 2s
      - light.turn_on:
          id: onboard_led
          brightness: 15%
          red: 80%
          green: 0%
          blue: 100%
light:
  <<: !include components/onboard_ws2812.yaml
