---
substitutions:
  device_name: diningroom-epl
  description: Dining Room Everything Presence Lite
  name: ${device_name}
  friendly_name: Dining Room EPL
  ld2450_tx_pin: GPIO17
  ld2450_rx_pin: GPIO16
  i2c_sda: GPIO21
  i2c_scl: GPIO22
  illuminance_update_interval: "2s"

packages:
  <<: !include_dir_named common
  i2c: !include components/i2c.yaml
  btproxy: !include components/bluetooth_proxy+tracker.yaml
  <<: !include devices/everything-presence-lite.yaml

esphome:
  name_add_mac_suffix: false

esp32:
  board: esp32dev

#Enable logging
logger:
#  baud_rate: 0 #disable UART logging

## override the Max distance from 600 to 700 cm w/ !extend
number:
  - id: !extend distance
    max_value: 700
    initial_value: 700
  - id: !extend zone2_begin_y
    max_value: 7000
  - id: !extend zone2_end_y
    max_value: 7000

