substitutions:
  device_name: edan-plug-fan
  name: Edan Fan
  description: Edan's Fan Plug (Cloudfree SmartPlug2)
  switch_restore_mode: ALWAYS_OFF
  #switch_restore_mode: RESTORE_DEFAULT_OFF
  #ipaddress: 192.168.1.200
  #wattage_calibration: 67.6 -> 11.0
  #amperage_calibration: 0.12 -> 0.08
  #voltage_calibration1: 0.0 -> 0.0
  #voltage_calibration2: 322.4 -> 118.3

packages:
  device: !include devices/aoycocr_x10s_common.yaml

logger:
