---
substitutions:
  device_name: esp32-bluetooth-proxy00
  name: bt-proxy00
  description: esphome bluetooth proxy
  board: esp32doit-devkit-v1

packages:
  <<: !include_dir_named common

<<: !include boards/esp32doit-devkit-v1.yaml
<<: !include components/bluetooth_proxy+tracker.yaml

esphome:
  name: ${device_name}
#  name_add_mac_suffix: true # causes issues w/ being found for ota/logs
  comment: ${description}

logger:
