---
# Upsy Desky config - based off of https://github.com/tjhorner/upsy-desky/blob/master/firmware/base.yaml (2024-04-29)
# and using https://github.com/tjhorner/esphome-standing-desk/blob/master/configs/template.yaml (which is needed by upsy-desky)
#
# Wiring mods needed to convert Upsy Desky to Lolin S3 mini(used cat6+keystones):
#   RJ45 Pin  GPIO Pin(upsy) S3     wire color
#   ---------------------------------------------
#   1         18 (mem)       18     orange/white
#   2         17 (rx)        44     orange
#   3         N/A (GND)      GND    green/white
#   4         16 (tx)        43     blue
#   5         N/A (+5V)      VBUS   blue/white
#   6         19             21     green
#   7         21 (up)        16     brown/white
#   8         22 (dwn)       17     brown

substitutions:
  device_name: office-desk
  name: "Office Desk"
  description: Office Desk controller (based on Upsy Desky - https://upsy-desky.tjhorner.dev)
  # Configurable options (Upsy Desky)
  desk_height_name: "Desk Height"
  target_desk_height_name: "Target Desk Height"

  # Standing Desk Component Config
  standing_desk_uart_rx_pin: "44"
  standing_desk_up_pin: "16"
  standing_desk_down_pin: "17"
  standing_desk_min_height: "25.2"
  standing_desk_max_height: "50.8"

  # Presets Addon Config
  button_bit1_pin: "16"
  button_bit2_pin: "17"
  button_bit4_pin: "21"
  button_m_pin: "18"

  # Runtime Config Defaults
  default_height_units: "in"  # Must be "in" or "cm"

packages:
  <<: !include_dir_named common
  board: !include boards/lolin_s3_mini.yaml
  bluetooth: !include components/bluetooth_proxy+tracker.yaml
  # i2c: !include components/i2c.yaml
  # Upsy Desky
  standing_desk: github://tjhorner/esphome-standing-desk/configs/template.yaml
  addon_presets: github://tjhorner/upsy-desky/firmware/addons/presets.yaml
  addon_runtime_config: github://tjhorner/upsy-desky/firmware/addons/runtime-config.yaml
  # below is for "stable" entity IDs for http API that we aren't using
  #addon_stable_ids: github://tjhorner/upsy-desky/firmware/addons/stable-ids.yaml

esphome:
  on_boot:
    then:
      - delay: 2s
      - light.turn_on:
          id: onboard_led
          brightness: 50%
          red: 80%
          green: 0%
          blue: 100%
      # Wakes up the desk and reports height
      - uart.write:
          id: handset_tx
          data: [0x0]

light:
  <<: !include components/onboard_ws2812.yaml

uart:
  id: handset_tx
  tx_pin: 43
  baud_rate: 9600
