---
substitutions:
  device_name: shop-tracker
  name: "Shop tracker"
  description: Shop ble proxy & device tracker
  onboard_led_gpio: GPIO7

packages:
  <<: !include_dir_named common
  board: !include boards/lolin_c3_mini.yaml

<<: !include components/bluetooth_proxy+tracker-single-core.yaml

esphome:
  platformio_options:
    board_build.flash_mode: dio
  on_boot:
    then:
      - delay: 2s
      - light.turn_on:
          id: onboard_led
          brightness: 15%
          red: 80%
          green: 0%
          blue: 100%

light:
  <<: !include components/onboard_ws2812.yaml
