---
substitutions:
  # Sonoff TH16 is the same as the TH10 w/ a 16A relay
  device_name: sonoff-th16-plug-0
  name: Sonoff TH16 Plug 0
  description: Sonoff th16

# esphome:
#   platform: ESP8266
#   board: esp01_1m
#   board_flash_mode: dout
#   on_boot:
#     #priority: -10
#     then:
#       - light.turn_on: blue_led

packages:
  <<: !include_dir_named common
  # board: !include boards/esp01_1m.yaml # added 'board:' to board file so only <<: is needed
  board: !include boards/esp01_1m.yaml

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    name: "${name} Button"
    on_press:
      - light.toggle: th10_1_relay
  - platform: status
    name: "${name} Status"

sensor:
  - platform: wifi_signal
    name: "${name} WiFi Signal"
    update_interval: 60s
#  - platform: dht
#    model: SI7021
#    pin: GPIO14
#    humidity:
#      name: "Bedroom Head/Air Switch Humidity"
#    temperature:
#      name: "${name} Switch Temp"
#    update_interval: 60s

switch:
  - platform: restart
    name: "${name} Restart"
    restore_mode: RESTORE_DEFAULT_OFF

output:
  - platform: esp8266_pwm
    id: TH10_1_blue_led
    pin:
      number: GPIO13
      inverted: true
  - platform: gpio
    id: relay
    pin: GPIO12

light:
  - platform: monochromatic
    name: "${name} blue LED"
    id: blue_led
    output: TH10_1_blue_led
  - platform: binary
    name: "${name} Relay"
    id: th10_1_relay
    output: relay
