substitutions:
  device_name: testy
  name: Testy Testerson
  device_id: testy
  description: test w/ light
  #web_server_password: !secret esphome_web_server_password
  onboard_led_gpio: GPIO38

packages:
  <<: !include_dir_named common
  board: !include boards/lolin_s3.yaml
  #component: !include components/web_server.yaml

#esphome:
#  on_boot:
#    then:
#      - delay: 2s
#      - light.turn_on:
#          id: ${device_id}_led
#          brightness: 15%

logger:
 # deassert_rts_dtr: true

#light:
#  - <<: !include components/onboard_ws2812.yaml
