# esp-12f testing

substitutions:
  device_name: esp12f0
  name: esp12f0
  description: testing esp-12f

packages:
  <<: !include_dir_named common
  board: !include boards/esp-12e.yaml
   #i2c: !include components/i2c.yaml

#Enable logging
logger:
  baud_rate: 115200
#  baud_rate: 0 #disable UART logging

status_led:
  pin: GPIO2

#sensor:
#  - <<: !include sensors/shtcx.yaml
#  - <<: !include sensors/bh1750.yaml
