# raspiaudio muse proto voice assistant

substitutions:
  device_name: voice0
  name: Voice Assistant 0
  description: voice assistant on Muse Proto

packages:
  <<: !include_dir_named common
  board: !include boards/esp-wrover-kit.yaml
   #i2c: !include components/i2c_esp8266.yaml

esphome:
  on_boot:
    priority: 10
    then:
     - lambda: |-
          gpio_reset_pin(GPIO_NUM_23);
          gpio_set_direction(GPIO_NUM_23, GPIO_MODE_OUTPUT);
          gpio_set_pull_mode(GPIO_NUM_23, GPIO_PULLDOWN_ONLY);
          gpio_set_level(GPIO_NUM_23, 0);

#Enable logging
logger:
  baud_rate: 115200
#  baud_rate: 0 #disable UART logging

#dashboard_import:
#  package_import_url: github://esphome/media-players/raspiaudio-muse-proto.yaml@main

i2s_audio:
  - i2s_lrclk_pin: GPIO25
    i2s_bclk_pin: GPIO5

microphone:
  - platform: i2s_audio
    id: board_microphone
    channel: left
    i2s_din_pin: GPIO35
    adc_type: external
    pdm: false

speaker:
  - platform: i2s_audio
    id: board_external_speakers
    dac_type: external
    #dac_type: internal
    i2s_dout_pin: GPIO26
    mode: mono
    #mode: stereo

voice_assistant:
  microphone: board_microphone
  speaker: board_external_speakers
  on_start:
    - light.turn_on:
        id: board_led
        blue: 100%
        red: 0%
        green: 0%
        effect: none
  on_tts_start:
    - light.turn_on:
        id: board_led
        blue: 60%
        red: 20%
        green: 20%
        effect: none
  on_tts_end:
    - light.turn_on:
        id: board_led
        blue: 60%
        red: 20%
        green: 20%
        effect: pulse
  on_end:
    - delay: 1s
    - wait_until:
        not:
          speaker.is_playing:
    - light.turn_off: board_led
  on_error:
    - light.turn_on:
        id: board_led
        blue: 0%
        red: 100%
        green: 0%
        effect: none
    - delay: 1s
    - light.turn_off: board_led

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      inverted: true
      mode:
        input: true
        pullup: true
    name: ${name} Action
    on_press:
      - voice_assistant.start:
    on_release:
      - voice_assistant.stop:

light:
  - platform: esp32_rmt_led_strip
    id: board_led
    name: None
    disabled_by_default: true
    pin: GPIO22
    default_transition_length: 0s
    chipset: WS2812
    num_leds: 1
    rgb_order: grb
    rmt_channel: 0
    effects:
      - pulse:
          transition_length: 250ms
          update_interval: 250ms
