# raspiaudio muse proto voice assistant

substitutions:
  device_name: voice0
  name: Voice Assistant 0
  description: voice assistant on Muse Proto

packages:
  <<: !include_dir_named common
  board: !include boards/esp-wrover-kit.yaml
   #i2c: !include components/i2c.yaml

esphome:
  on_boot:
    priority: 10
    then:
     - media_player.play_media: 'https://ha.i.shadowed.net/api/tts_proxy/1ec123bde89c72541bc0e4d8e15baac0ff146637_en-us_a877e2b3bf_tts.piper.wav'
  project:
    name: raspiaudio.muse-proto
    version: "1.0"
  min_version: 2023.5.3

dashboard_import:
  package_import_url: github://esphome/media-players/raspiaudio-muse-proto.yaml@main

logger:
  baud_rate: 115200
#  baud_rate: 0 #disable UART logging

#dashboard_import:
#  package_import_url: github://esphome/media-players/raspiaudio-muse-proto.yaml@main

i2s_audio:
  - i2s_lrclk_pin: GPIO25
    i2s_bclk_pin: GPIO5

microphone:
  - platform: i2s_audio
    id: board_microphone
    channel: left
    i2s_din_pin: GPIO35
    adc_type: external
    pdm: false

speaker:
  - platform: i2s_audio
    id: board_external_speakers
    dac_type: external
    i2s_dout_pin: GPIO26
    mode: mono

media_player:
  - platform: i2s_audio
    id: media_out
    name: None
    dac_type: external
    i2s_dout_pin: GPIO26
    mode: mono
    mute_pin:
      number: GPIO21
      inverted: true

voice_assistant:
  microphone: board_microphone
  speaker: board_external_speakers
  on_start:
    - media_player.volume_set: 100%
    - light.turn_on:
        id: board_led
        brightness: 50%
        blue: 100%
        red: 0%
        green: 0%
        effect: none
  on_tts_start:
    - light.turn_on:
        id: board_led
        brightness: 50%
        blue: 60%
        red: 20%
        green: 20%
        effect: none
  on_tts_end:
    - delay: 0.5s
    - light.turn_on:
        id: board_led
        brightness: 50%
        blue: 60%
        red: 20%
        green: 20%
        effect: pulse
  on_end:
    - delay: 1s
    - wait_until:
        not:
          speaker.is_playing:
    - light.turn_off: board_led
  on_error:
    - light.turn_on:
        id: board_led
        brightness: 50%
        blue: 0%
        red: 100%
        green: 0%
        effect: none
    - delay: 1s
    - light.turn_off: board_led

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      inverted: true
      mode:
        input: true
        pullup: true
    name: Assistant0 Action
    on_multi_click:
      - timing:
          - ON FOR AT MOST 350ms
          - OFF FOR AT LEAST 10ms
        then:
          - media_player.toggle: media_out
      - timing:
          - ON FOR AT LEAST 350ms
        then:
          - voice_assistant.start:
      - timing:
          - ON FOR AT LEAST 350ms
          - OFF FOR AT LEAST 10ms
        then:
          - voice_assistant.stop:

light:
  - platform: esp32_rmt_led_strip
    id: board_led
    name: None
    disabled_by_default: true
    pin: GPIO22
    default_transition_length: 0s
    chipset: WS2812
    num_leds: 1
    rgb_order: grb
    rmt_channel: 0
    effects:
      - pulse:
          transition_length: 250ms
          update_interval: 250ms
