---
# OTA (Over The Air) component
#
# Contains my common Wi-Fi setup.
#
# https://esphome.io/components/ota.html
#
substitutions:
  ota_password: !secret esphome_ota_password

ota:
  platform: esphome
  id: component_ota
  password: "${ota_password}"

# in 2024.6.0 safe_mode is now a top level component'
safe_mode:
  reboot_timeout: 10min
  num_attempts: 5
