- platform: ethernet_info
  ip_address:
    name: IP Address
    address_0:
      name: IP Address 0
    address_1:
      name: IP Address 1
    address_2:
      name: IP Address 2
    address_3:
      name: IP Address 3
    address_4:
      name: IP Address 4
  dns_address:
    name: DNS Address
  mac_address:
    name: MAC Address
