# Wemos C3 mini
#
# https://www.wemos.cc/en/latest/c3/c3_mini.html
# https://docs.platformio.org/en/latest/boards/espressif32/lolin_c3_mini.html
#
esp32:
  board: lolin_c3_mini
  framework:
    type: arduino
