---
# M5Stack AtomS3 (& Lite)
#
# https://docs.platformio.org/en/latest/boards/espressif32/m5stack-atoms3.html
#
# https://docs.m5stack.com/en/core/AtomS3
# https://docs.m5stack.com/en/core/AtomS3%20Lite
#
# AtomS3 Lite is the same as the non Lite w/o the display

substitutions:
  onboard_led_gpio: GPIO35
  onboard_led_rgb_order: GBR

esp32:
  board: m5stack-atoms3
  variant: esp32s3
  framework:
    type: esp-idf
