---
# remote package documentation: https://esphome.io/guides/configuration-types#remote-git-packages
#
# Pull the Everything Presence Lite config from github
# packages:    # include this file in "packages:"

remote_package_shorthand: github://EverythingSmartHome/everything-presence-lite/everything-presence-lite-ha.yaml@main
#remote_package_files:
#  url: https://github.com/EverythingSmartHome/everything-presence-lite
#  files: [ everything-presence-lite-ha.yaml ]
#  ref: main

## extend the Max distance from 600 to 700 cm
## moved to files this is included from to avoid it throwing "Shorthand only for strings." error 🤷
#number:
#  - id: !extend distance
#    max_value: 700
#    initial_value: 700
