# Common code for Outon S1 Lamp

packages:
  <<: !include_dir_named ../common
  board: !include ../boards/bk7231n_cbu.yaml
  webserver: !include ../components/web_server.yaml

# ensure logger isn't using serial port, needed for UART
logger:
  baud_rate: 0
#web_server:
captive_portal:
mdns:
debug:
  update_interval: 30s

text_sensor:
  - platform: debug
    reset_reason:
      name: Reset Reason
  - platform: libretiny
    version:
      name: LibreTiny Version

sensor:
  - platform: uptime
    name: Uptime

## seems to work, nfi what it's measuring
#  - platform: adc
#    pin: ADC3
#    name: unknown_adc
#    raw: true
#    update_interval: 30s

## logger must not be using serial port (tx/rx pins)
# uart:
#   rx_pin: GPIO10
#   tx_pin: GPIO11
#   baud_rate: 9600
# tuya:

output:
  - platform: libretiny_pwm
    id: output_cold
    pin: P7
  - platform: libretiny_pwm
    id: output_warm
    pin: P8

light:
  - platform: cwww
    id: light_cwww
    name: ${name} Light
    restore_mode: RESTORE_DEFAULT_OFF
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2700 K
    cold_white: output_cold
    warm_white: output_warm

# https://esphome.io/components/light/beken_spi_led_strip 
  - platform: beken_spi_led_strip
    name: ${name} RGB
    rgb_order: RGB
    pin: P16
    num_leds: 32
    chipset: ws2812
