# remote package documentation: https://esphome.io/guides/configuration-types#remote-git-packages
#
# Pull the M5Stack Atom Echo voice-assistant config from github
packages:
  remote_package: github://esphome/firmware/voice-assistant/esp32-s3-box.yaml@main
