---
# remote package documentation:
# https://esphome.io/guides/configuration-types#remote-git-packages
#

# Pull the M5Stack Atom Echo voice-assistant config from github
packages:
  # remote_package: github://esphome/firmware/voice-assistant/m5stack-atom-echo.yaml@main
  remote_package: github://esphome/wake-word-voice-assistants/m5stack-atom-echo/m5stack-atom-echo.yaml@main

# ota: !remove
# update: !remove

# :(  This feature is only available with frameworks ['arduino'].
# media_player:
#   - platform: i2s_audio
#     id: echo_speaker
#     i2s_dout_pin: GPIO22
#     dac_type: external
#     mode: mono
